// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vutoglthnjuhgayyatzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1dG9nbHRobmp1aGdheXlhdHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODE4ODcsImV4cCI6MjA3MjI1Nzg4N30.IZAowTjkYmmY_5aDrXJ1n0B3CKgmAONKFytHS2yMOtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});